### ISSUE TITLE
Ariadna Belén Bernabé Juárez: Infografía

### ISSUE THREAD

**Issue by 23620030** [SistemasTecTlaxiaco/infografia-23620030#2]
[Bernabe Juárez Ariadna Belén info1.pdf](https://github.com/SistemasTecTlaxiaco/infografia-23620030/files/12500692/Bernabe.Juarez.Ariadna.Belen.info1.pdf)

**Comment by Felix-Angel** [comment]
Redacción y ortografía: 10%
Exposición de ideas centrales 13% (No cuenta con 10 ideas principales)
Organización de  la información: 15%
Uso de imágenes y colores: 15%
Presentación visual: 15%
Referencias: 15%
Presentación: 15%
Calificación: 19.6/20
Calificado por equipo "Mayra, Daniel, Diego, Félix"

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
